# Generated by Django 2.0.7 on 2018-10-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20181014_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='character_gender',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='character_name',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
