# Generated by Django 2.0.7 on 2018-10-14 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20181014_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='character_gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='character_name',
        ),
    ]
