# Generated by Django 2.0.7 on 2018-10-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_auto_20181014_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='character_gender',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
