# Generated by Django 2.0.7 on 2018-10-15 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20181014_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='character_gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='character_name',
        ),
    ]
