# Generated by Django 2.0.7 on 2018-10-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_auto_20181014_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='playerX',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='playerY',
            field=models.IntegerField(null=True),
        ),
    ]
