# Generated by Django 2.0.7 on 2018-10-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_auto_20181015_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='characterGender',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='characterName',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
