# Generated by Django 2.0.7 on 2018-10-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_auto_20181015_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='characterGender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='', max_length=9, null=True),
        ),
    ]
