# Generated by Django 2.0.7 on 2018-10-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_auto_20181018_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='actualXp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
