# Generated by Django 2.0.7 on 2018-10-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_auto_20181020_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='highestScoreBreakout',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='highestScoreFishing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='highestScoreFlappyBird',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='highestScoreGuitarHero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='highestScoreMaze',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='highestScorePong',
            field=models.IntegerField(null=True),
        ),
    ]
